version: "3.2"
services:
  apollo-configservice:
    container_name: apollo-configservice
    build:
      context: apollo-configservice/
      args:
        CONFIG_SERVER_PORT: 9080
    image: apollo-configservice
    volumes:
      - "/opt/logs/9080/100003171:/opt/logs/100003171"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://10.0.17.122:3306/apolloconfigdb?characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Pdhn^456
      - EUREKA.INSTANCE.IP-ADDRESS=120.46.151.207
    restart: always
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 300M
        reservations:
          cpus: '0.2'
          memory: 200M

  apollo-adminservice:
    depends_on:
      - apollo-configservice
    container_name: apollo-adminservice
    build:
      context: apollo-adminservice/
      args:
        CONFIG_SERVER_PORT: 9080
        ADMIN_SERVER_PORT: 9090
    image: apollo-adminservice
    volumes:
      - "/opt/logs/9080/100003172:/opt/logs/100003172"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://10.0.17.122:3306/apolloconfigdb?characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Pdhn^456
      - EUREKA.INSTANCE.IP-ADDRESS=120.46.151.207
    restart: always
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 300M
        reservations:
          cpus: '0.2'
          memory: 200M
