version: "3.2"    
services:  
  apollo-configservice-data:
    container_name: apollo-configservice-data
    build:
      context: apollo-configservice/
      args:
        CONFIG_SERVER_PORT: 8080
    image: apollo-configservice-data
    ports:
      - "8080" 
    volumes:
      - "/opt/logs/data/100003171:/opt/logs/100003171"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://182.61.41.102:3306/apolloconfigdbdata?characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - EUREKA.INSTANCE.IP-ADDRESS=182.61.41.102
    restart: always
    network_mode: host    
    deploy:
      resources:
         limits:
            cpus: '0.3'
            memory: 300M
         reservations:
            cpus: '0.2'
            memory: 200M

  apollo-adminservice-data:
    depends_on:
      - apollo-configservice-data
    container_name: apollo-adminservice-data
    build:
      context: apollo-adminservice/
      args:
        ADMIN_SERVER_PORT: 8090
    image: apollo-adminservice-data
    ports:
      - "8090"
    volumes:
      - "/opt/logs/data/100003172:/opt/logs/100003172"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://182.61.41.102:3306/apolloconfigdbdata?characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - EUREKA.INSTANCE.IP-ADDRESS=182.61.41.102
    restart: always
    network_mode: host
    deploy:
      resources:
         limits:
            cpus: '0.3'
            memory: 300M
         reservations:
            cpus: '0.2'
            memory: 200M
