version: '3'
networks:
  monitor:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    privileged: true
    restart: always
    volumes:
    - /usr/local/src/config/prometheus.yml:/etc/prometheus/prometheus.yml
    - /usr/local/src/config/node_down.yml:/etc/prometheus/node_down.yml
    ports:
    - "9091:9090"
    networks:
    - monitor
    links:
    - alertmanager
    - node-exporter


  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    hostname: alertmanager
    restart: always
    privileged: true
    volumes:
    - /usr/local/src/config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
    - "9093:9093"
    networks:
    - monitor


  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    privileged: true
    restart: always
    ports:
    - "3000:3000"
    networks:
    - monitor
    links:
    - prometheus

  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    hostname: node-exporter
    restart: always
    privileged: true
    ports:
    - "9100:9100"
    networks:
    - monitor





