version: "3"
services:
  seata-server:
    image: seataio/seata-server:1.4.2
    container_name: seata-server
    privileged: true
    ports:
    - "8091:8091"
    volumes:
    - ${PWD}/conf/registry.conf:/seata-server/resources/registry.conf
    - ${PWD}/logs:/root/logs
    environment:
    - SERVER_NODE=1
    - SEATA_IP=10.0.17.92
    - SEATA_PORT=8091
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 300M