version: '3'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /toony/redis/data:/data
      - /toony/redis/conf/redis.conf:/etc/redis/redis.conf
      - /mydata/mysql/conf:/etc/mysql
    restart: always
    command: redis-server /etc/redis/redis.conf
    environment:
      - COMPOSE_PROJECT_NAME=redis-server