global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_from: '493478910@qq.com'
  smtp_auth_username: '493478910@qq.com'
  smtp_auth_password: 'jkfgivftxghvcabd'
  smtp_require_tls: false
  smtp_hello: 'qq.com'


route:
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'mail-receiver'
receivers:
- name: 'mail-receiver'
  email_configs:
  - to: 'zhangliang1024_job@126.com'