version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /toony/mysql/log:/var/log/mysql
      - /toony/mysql/data:/var/lib/mysql
      - /toony/mysql/conf:/etc/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - COMPOSE_PROJECT_NAME=mysql-server
